database_host: localhost
database_username: postgres
database_password: ""

bugsnag_api_key: BUGSNAG_API_KEY

# aws_access_key_id: AWS_ACCESS_KEY_ID
# aws_secret_access_key: AWS_SECRET_ACCESS_KEY
# aws_region: AWS_REGION
# aws_bucket: AWS_BUCKET
# mailgun_api_key: MAILGUN_API_KEY

development:
  secret_key_base: #{SecureRandom.hex(64)}
  database_name: #{app_name}_development
test:
  secret_key_base: #{SecureRandom.hex(64)}
  database_name: #{app_name}_test
