name: Deploy staging

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    branches: [staging]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    uses: infinum/default_rails_template/.github/workflows/deploy.yml@v1
    with:
      environment: staging
      branch: staging
      deployers: 'DEPLOY USERS GO HERE' # Example: '@github_username1 @github_username2'
      # slack_notification_channel: 'slack-channel-name-without-hash-symbol' # UNCOMMENT THIS IF YOU WANT SLACK NOTIFICATIONS, DELETE OTHERWISE
      # notify_on: 'all' # Possible values: 'success', 'failure', or 'all'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
      # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} # UNCOMMENT THIS IF YOU WANT SLACK NOTIFICATIONS, DELETE OTHERWISE

  # publish_docs: # UNCOMMENT THIS IF YOU USE DOX FOR API DOCUMENTATION, DELETE OTHERWISE
  #   name: Publish docs
  #   needs: [deploy]
  #   uses: infinum/default_rails_template/.github/workflows/publish-docs.yml@v1
  #   with:
  #     postgres_image: '13.2'
  #     environment: staging
  #     branch: staging
  #   secrets:
  #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
  #     VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
  #     VAULT_AUTH_METHOD: ${{ secrets.VAULT_AUTH_METHOD }}
  #     VAULT_AUTH_ROLE_ID: ${{ secrets.VAULT_AUTH_ROLE_ID }}
  #     VAULT_AUTH_SECRET_ID: ${{ secrets.VAULT_AUTH_SECRET_ID }}
