name: Build, Test, & Push Production Docker Image
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build_image:
    uses: infinum/default_rails_template/.github/workflows/build-image.yml@v1
    with:
      postgres_image: '13.6'
      rails_env: 'production'
    secrets:
      AWS_IAM_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
      AWS_IAM_ACCESS_SECRET_KEY: ${{ secrets.AWS_IAM_ACCESS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMAGE: ${{ secrets.AWS_ECR_REPO_URL }}/${{ secrets.AWS_ECR_REPO_NAME }}
